# Generated by Django 2.0 on 2020-06-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('medical_history', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('medical_id', models.CharField(max_length=50)),
            ],
        ),
    ]
