# Generated by Django 2.0 on 2020-06-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20200613_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='medical_id',
        ),
    ]
