# Generated by Django 2.0 on 2020-06-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20200616_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_of_app', models.DateTimeField(auto_now_add=True)),
                ('disease', models.CharField(max_length=50)),
                ('date_for_app', models.DateField()),
                ('time_for_app', models.TimeField()),
                ('doctor', models.CharField(max_length=50)),
            ],
        ),
    ]
