# Generated by Django 2.0 on 2020-06-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete='DO_NOTHING', to='patient.registrationp'),
        ),
    ]
