# Generated by Django 2.0 on 2020-06-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_registrationd_department'),
        ('patient', '0009_auto_20200619_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doct_key',
            field=models.ForeignKey(null=True, on_delete='DO_NOTHING', to='doctor.registrationd'),
        ),
    ]
