# Generated by Django 2.0 on 2020-06-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_auto_20200619_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_approval', models.DateField(auto_now_add=True)),
                ('fieldName', models.TimeField(auto_now_add=True)),
                ('changes_made', models.CharField(default='pending', max_length=150)),
            ],
        ),
    ]
