# Generated by Django 2.0 on 2020-06-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_report'),
        ('patient', '0013_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date_of_approval',
            new_name='date_of_notificaton',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='fieldName',
            new_name='time_of_notificaton',
        ),
        migrations.AddField(
            model_name='notification',
            name='doct_key',
            field=models.ForeignKey(null=True, on_delete='DO_NOTHING', to='doctor.registrationd'),
        ),
        migrations.AddField(
            model_name='notification',
            name='patient',
            field=models.ForeignKey(null=True, on_delete='DO_NOTHING', to='patient.registrationp'),
        ),
    ]
