# Generated by Django 2.0 on 2020-06-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_report'),
        ('patient', '0015_auto_20200620_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='appntmnt',
        ),
        migrations.AddField(
            model_name='notification',
            name='doct_key',
            field=models.ForeignKey(null=True, on_delete='DO_NOTHING', to='doctor.registrationd'),
        ),
        migrations.AddField(
            model_name='notification',
            name='patient',
            field=models.ForeignKey(null=True, on_delete='DO_NOTHING', to='patient.registrationp'),
        ),
    ]
