# Generated by Django 2.0 on 2020-06-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_auto_20200621_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='doct_key',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='patient',
        ),
        migrations.AddField(
            model_name='notification',
            name='appntment',
            field=models.ForeignKey(null=True, on_delete='DO_NOTHING', to='patient.appointment'),
        ),
    ]
