# Generated by Django 2.0 on 2020-06-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_auto_20200621_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='registrationp',
            name='user_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='change_made_by',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
