# Generated by Django 2.0 on 2020-06-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_notification_changes_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(default='active', max_length=150),
        ),
    ]
