# Generated by Django 2.0 on 2020-06-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_notification_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date_of_notificaton',
            new_name='date_of_notification',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='time_of_notificaton',
            new_name='time_of_notification',
        ),
    ]
