# Generated by Django 2.0 on 2020-06-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0025_auto_20200621_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status_of_report',
            field=models.CharField(default='pending', max_length=150),
        ),
    ]
