# Generated by Django 2.0 on 2020-06-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0026_appointment_status_of_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationp',
            name='medical_history',
        ),
    ]
