# Generated by Django 2.0 on 2020-06-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='experience_yr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='qualifications',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
