# Generated by Django 2.0 on 2020-06-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20200613_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='qualification',
            field=models.CharField(max_length=256),
        ),
    ]
