# Generated by Django 2.0 on 2020-06-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20200613_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='experience_yr',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='qualification',
        ),
    ]
