# Generated by Django 2.0 on 2020-06-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20200613_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
