# Generated by Django 2.0 on 2020-06-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_registration_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registration',
            new_name='registrationd',
        ),
    ]
