# Generated by Django 2.0 on 2020-06-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20200616_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationd',
            name='department',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
