# Generated by Django 2.0 on 2020-06-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_registrationd_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationd',
            name='medical_id',
        ),
    ]
