# Generated by Django 2.0 on 2020-06-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_notification'),
        ('doctor', '0011_remove_registrationd_medical_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(max_length=150)),
                ('doct_key', models.ForeignKey(null=True, on_delete='DO_NOTHING', to='doctor.registrationd')),
                ('patient', models.ForeignKey(null=True, on_delete='DO_NOTHING', to='patient.registrationp')),
            ],
        ),
    ]
