# Generated by Django 2.0 on 2020-06-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0025_auto_20200621_1800'),
        ('doctor', '0012_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='doct_key',
        ),
        migrations.RemoveField(
            model_name='report',
            name='patient',
        ),
        migrations.AddField(
            model_name='report',
            name='appntment',
            field=models.ForeignKey(null=True, on_delete='DO_NOTHING', to='patient.appointment'),
        ),
        migrations.AddField(
            model_name='report',
            name='further_ins',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
