# Generated by Django 2.0 on 2020-06-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_remove_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_of_report',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='time_of_report',
            field=models.TimeField(auto_now=True),
        ),
    ]
